@startuml Diagrama_de_Estados

title Diagrama de Estados del Edificio

skinparam {
    NoteBackgroundColor #whiteSmoke
}

hide empty members

[*] --> Disponible : Acceso Habilitado
[*] --> NoDisponible : Acceso Denegado
Disponible --> NoDisponible : Acceso Denegado
NoDisponible --> Disponible : Acceso Habilitado

@enduml