@startuml
title State Diagram - CCCF
state ShoppingCenter {
[*] --> SC_Closed
SC_Closed -right-> [*]
    SC_Closed --> SC_Opened : 9 am
    state SC_Opened {
    [*] --> SC_OpenDoors
    SC_OpenDoors --> SC_ClosedDoors: 8:40 pm
    SC_Opened --> SC_Closed : no customers\nleft
    }


state Queue {
    Q_Empty --> Q_Receiving: customer\narrives
    Q_Receiving --> Q_Empty: no customers\nleft
    Q_Receiving --> Q_Receiving: customers\nkeep arriving
    SC_Opened --> Q_Empty: 9 am
}

CashRegister -left-> SC_Opened: all customers\nserved

state CashRegister {
    state CR_Closed
    state CR_Opened{
    CR_Closed --> CR_Empty: (queue/(nCRO+1)) > 5
    CR_Empty --> CR_Closed: shift change\nqueue < ((nCRO-1)*5)
    CR_Empty --> CR_Serving: items>=5
    CR_Serving --> CR_Empty: items=0
    CR_Serving --> CR_Serving: packItems>1
    }
}
Q_Receiving --> CR_Empty
SC_Opened --> CR_Opened: 9 am

}
@enduml
