@startuml
package Vistas {
class VistaDelMundo {
}
}

package Controladores {
 class controladorDePersonajes {
}

class controladorDeMovimiento {
}

class controladorDeInput {
}

class controladorDeMovimientoRandom {
}

class controladorDeLimite {
}

class controladorDeTiempo {
}
}

package Models {
 class mundo{
+ tiempo
+ personajes
+ mapa
}
class mapa{
 + tiles
}
class tiles{
 + efectoEnVelocidad
}
abstract class personaje {
+ velocidad
+ transporteEnUso
+ posición
}
class transporte{
 + tilesPasables
 + efectoEnVelocidad
}
class jugable{}
class npc{}
}

package Utils {
 enum Tiles {
 Suelo
Arena
Paredes
Cesped Alto
Cesped Medio
Cesped Bajo
Aguas
Aguas Turbias
Montaña
}


enum TiposDeTransporte {
 Caballo
 Bote
Alfombra
APie
}
}



mundo -- mapa
mapa -- tiles
mundo .. personaje
tiles -- transporte
transporte -- personaje
personaje -- jugable
personaje -- npc

controladorDeMovimiento -- controladorDeInput
controladorDeMovimiento -- controladorDeMovimientoRandom
controladorDePersonajes -- controladorDeMovimiento
controladorDePersonajes -- personaje
controladorDeLimite -- mapa
controladorDeLimite  -- personaje
controladorDeTiempo -- mundo
VistaDelMundo -- mundo

transporte -- TiposDeTransporte
tiles -- Tiles
@enduml