@startuml

skinparam linetype polyline

title Class Diagram - CCCF

class ShoppingCenter {
    - openingHour
    - closingHour
    - time
    - arrivalProbability
    - isOpen
}

class AttentionCenter{
    - emptyCashRegisters
}

class CashRegister {
    - id
    - currentCashier
    - timePerItemPack
    - isOcuppied
    - isOpen
    - remainingPacks
}

class Customer {
    - id
    - numberOfItemPacks
}

class Queue {
    - size
}

class Cashier {
    - id
    - name
    - workShift
    - workBreak
    - isServing
}

class DataLog{

}

class Time{

}


ShoppingCenter "1" *-- "1" Queue
ShoppingCenter "1" o-- "*" Customer
ShoppingCenter "1" *-- "*" Cashier
ShoppingCenter "1" *-- "*" CashRegister

Queue -- AttentionCenter
Queue --  Customer
Queue .right. DataLog


AttentionCenter -left- Customer
AttentionCenter -- CashRegister
AttentionCenter .. Time

CashRegister -- Cashier
CashRegister -- Customer
CashRegister .. Time

ShoppingCenter ..R Time
ShoppingCenter .. DataLog
CashRegister .right. DataLog

@enduml