@startuml
title Modelo del dominio Apiradora

class Habitacion {

    +dimension
}

class Elemento { 

    +mueble
    +nivelSuciedad
    +posicion
}

class Aspiradora {

    +posicion
}

class Gato {

    +posicion 
}

Habitacion -- Elemento
Habitacion -- Aspiradora
Habitacion -- Gato

@enduml