@startuml

[*] --> Inicio: Inicia la batalla
Inicio --> SeleccionArma: Héroe elige arma
Inicio --> AtaqueVampiro: Vampiro ataca

SeleccionArma --> AtaqueHeroe: Héroe ataca
AtaqueVampiro --> DefensaHeroe: Héroe decide defenderse
AtaqueVampiro --> RecibeAtaque: Héroe recibe ataque
DefensaHeroe --> AtaqueDefendido: Defensa exitosa
DefensaHeroe --> RecibeAtaque: Defensa fallida
AtaqueHeroe --> RecibeAtaqueVampiro: Vampiro recibe ataque
RecibeAtaque --> AtaqueVampiro: Vampiro contraataca
RecibeAtaqueVampiro --> SeleccionArma: Héroe elige arma nuevamente

AtaqueHeroe --> HeroeDesmayado: Energía Héroe < 30
AtaqueVampiro --> VampiroDesmayado: Energía Vampiro < 20

HeroeDesmayado --> RecuperacionHeroe: Recupera 2 puntos de energía por turno
VampiroDesmayado --> RecuperacionVampiro: Recupera 2 puntos de energía por turno
RecuperacionHeroe --> SeleccionArma: Energía Héroe >= 30
RecuperacionVampiro --> AtaqueVampiro: Energía Vampiro >= 20

SeleccionArma --> UsoPocion: Héroe usa poción
UsoPocion --> EsperaPocion: Espera 3 turnos
EsperaPocion --> RecibeAtaque: Héroe recibe ataques durante espera
EsperaPocion --> RecuperacionTotalHeroe: Finaliza espera

RecibeAtaque --> FinVampiroGana: Héroe HP <= 0
RecibeAtaqueVampiro --> FinHeroeGana: Vampiro HP <= 0
RecuperacionTotalHeroe --> SeleccionArma: Héroe recupera toda su energía

FinHeroeGana --> [*]
FinVampiroGana --> [*]

@enduml
