@startuml
title Diagrama de Estados de la Aspiradora

[*] --> Apagada

Apagada -r-> Encendida
Encendida -r-> Apagada
Encendida -r-> Limpiando
Limpiando --> Aspirando 
Aspirando -r-> Limpiando 
Limpiando -r-> Encendida 
Limpiando -r-> Apagada
Limpiando -r-> Limpiando
Apagada --> [*]

@enduml