@startuml
title Modelo del dominio Apiradora

class Superficie { 

    +elemento
    +nivelSuciedad
    +posicion
}

class Habitacion {

    +dimension
}

class Aspiradora {

    +posicion
}

class Gato {

    +posicion 
}

Habitacion -- Superficie
Habitacion -- Aspiradora
Habitacion -- Gato

@enduml