@startuml Modelo del dominio Ticket
'https://plantuml.com/sequence-diagram
title Modelo del dominio Apiradora

class superficie { 

    +elemento
    +nivelSuciedad
    +posicion
}

class habitacion {

    +dimension
}

class aspiradora {

    +bateria
    +capacidad
    +posicion
}

class gato {

    +posicion 
}

habitacion -- superficie
superficie -- aspiradora
superficie -- gato

@enduml