@startuml
title Diagrama de Estados de la Aspiradora

[*] --> Apagada

Apagada --> Encendida
Encendida --> Apagada
state Encendida{
    Limpiando --> Aspirando 
    Aspirando -r-> Limpiando 
    Limpiando -r-> Limpiando
}
Apagada -r-> Cargando
Cargando -r-> Apagada
Apagada --> [*]

@enduml