@startuml CasoDeUsoAvanzarElTiempo

start
:Recibir cantidad de minutos\npara avanzar;
if (¿Minutos > 60?) then (sí)
    :Avanzar hora;
    :Ajustar minutos;
else (no)
    :Incrementar minutos;
endif
if (¿Hora > 23?) then (sí)
    :Resetear a hora cero;
else (no)
    :Mantener hora actual;
endif
:Verificar cambio de tiempo\ndel día;
if (¿Es momento de cambiar de momento?) then (sí)
    :Ajustar el momento del día \n (Mañana, Tarde, Noche);
else (no)
    :Mantener tiempo actual;
endif
stop

@enduml
