@startuml

[*] --> Inicio: Inicia la batalla
Inicio --> SeleccionArma: Héroe elige arma
Inicio --> AtaqueVampiro: Vampiro ataca

SeleccionArma --> AtaqueHeroe: Héroe ataca
AtaqueVampiro --> [*]: Héroe HP <= 0
AtaqueVampiro --> DefensaHeroe: Héroe decide defenderse

DefensaHeroe --> AtaqueDefendido: Defensa exitosa
DefensaHeroe --> RecibeAtaque: Defensa fallida
RecibeAtaque --> AtaqueVampiro: Vampiro contraataca
RecibeAtaque --> [*]: Héroe HP <= 0

AtaqueHeroe --> RecibeAtaqueVampiro: Vampiro recibe ataque
RecibeAtaqueVampiro --> SeleccionArma: Héroe elige arma nuevamente
RecibeAtaqueVampiro --> [*]: Vampiro HP <= 0

AtaqueHeroe --> HeroeDesmayado: Energía Héroe < 30
AtaqueVampiro --> VampiroDesmayado: Energía Vampiro < 20

HeroeDesmayado --> FinVampiroGana: Héroe HP <= 0
VampiroDesmayado --> FinHeroeGana: Vampiro HP <= 0

SeleccionArma --> EsperaPocion: Héroe usa poción
EsperaPocion --> RecibeAtaque: Héroe recibe ataques durante espera
EsperaPocion --> RecuperacionTotalHeroe: Finaliza espera

FinHeroeGana --> [*]
FinVampiroGana --> [*]

@enduml