[*] --> movimientoAscensor
[*] --> ocupaciónAscensor
state movimientoAscensor{
AscensorParadado --> AscensorMoviendose
AscensorMoviendose --> AscensorParadado
}
state ocupaciónAscensor{
    AscensorOcupado --> AscensorLibre
    AscensorLibre --> AscensorOcupado
}
