@startuml
title Caso de Uso - CustomerWaiting

left to right direction
actor Customer as cust
actor Employee as emp

rectangle "CustomerWaiting" {
    usecase "Serve at Cash Register" as UC1
    usecase "Abandon Queue" as UC2
}

emp --> UC1
cust --> UC2
@enduml
