@startuml
title Caso de Uso - ShoppingCenterOpened

left to right direction
actor Employee as emp
actor Customer as cust

rectangle "ShoppingCenterOpened" {
    usecase "Register Customer Arrival" as UC1
    usecase "Close Shopping Center" as UC2
}

cust --> UC1
emp --> UC2
@enduml
