@startuml
title Caso de Uso - ShoppingCenterClosed

left to right direction
actor Employee as emp

rectangle "ShoppingCenterClosed" {
    usecase "Open Shopping Center" as UC1
    usecase "End Day" as UC2
}

emp --> UC1
emp --> UC2
@enduml
