@startuml
title Caso de Uso - CustomerSelectingProducts

left to right direction
actor Customer as cust

rectangle "CustomerSelectingProducts" {
    usecase "Join Queue" as UC1
    usecase "Continue Shopping" as UC2
}

cust --> UC1
cust --> UC2
@enduml
