@startuml Diagrama_de_Objetos

title Diagrama de Objetos

skinparam {
    NoteBackgroundColor #whiteSmoke
}

hide empty members

class "ASCENSOR 0:ASCENSOR"
{
    ID: 0
    ID de Planta: 2
    Personas en el Ascensor: 2
    Plantas a las que se dirige: 1, 0
    Dirección: Bajando
    Capacidad: 6
}

class "JUAN:PERSONA"
{
    ID : 0
    Origen: Planta 0
    Tiempo en Planta: 10
    Destino: Planta 1
}

class "PEDRO:PERSONA"
{
    ID : 1
    Origen: Planta 1
    Tiempo en Planta: 5
    Destino: Planta 0
}

class "CUADRO DE MANDO:CUADRO DE MANDO"
{
    Solicitudes de Ascensores: 10
    Solicitudes de Planta: 5
}

class "PLANTA 0:PLANTA"
{
    ID: 0
    Nombre planta: Planta 0
    Personas Cambiando de Planta : 2
    Personas en planta: 100
}

class "PLANTA 1:PLANTA"
{
    ID: 1
    Nombre planta: Planta 1
    Personas en planta: 75
    Personas Cambiando de Planta : 1
}

class "PLANTA 2:PLANTA"
{
    ID: 2
    Nombre planta: Planta 2
    Personas en planta: 50
    Personas Cambiando de Planta : 0
}

class "UNEATLANTICO:EDIFICIO"
{
    Plantas: 3
    Ascensores: 2
    Panel de Control : 1
}

"UNEATLANTICO:EDIFICIO" *-- "PLANTA 0:PLANTA" : Tiene
"UNEATLANTICO:EDIFICIO" *-- "PLANTA 1:PLANTA" : Tiene
"UNEATLANTICO:EDIFICIO" *-- "PLANTA 2:PLANTA" : Tiene

"PLANTA 0:PLANTA" o-- "JUAN:PERSONA" : Tiene
"PLANTA 1:PLANTA" o-- "PEDRO:PERSONA" : Tiene

"PLANTA 0:PLANTA" --> "ASCENSOR 0:ASCENSOR" : Tiene Acceso
"PLANTA 1:PLANTA" --> "ASCENSOR 0:ASCENSOR" : Tiene Acceso

"JUAN:PERSONA" ..> "ASCENSOR 0:ASCENSOR" : Utiliza
"PEDRO:PERSONA" ..> "ASCENSOR 0:ASCENSOR" : Utiliza

"JUAN:PERSONA" ..> "CUADRO DE MANDO:CUADRO DE MANDO" : Solicita al
"PEDRO:PERSONA" ..> "CUADRO DE MANDO:CUADRO DE MANDO" : Solicita al

"CUADRO DE MANDO:CUADRO DE MANDO" --> "ASCENSOR 0:ASCENSOR" : Gobierna
@enduml