@startuml PyMundoObjects

object World {
    maps = List<Map>{Map1, Map2}
    time = TimeInstance
    entities = List<Entity>{Character1, Transport1}
}

object TimeInstance {
    currentTime = "1235"
}

object Map1 {
    tiles = List<Tile>{Tile1, Tile2}
}

object Map2 {
    tiles = List<Tile>{Tile3, Tile4}
}

object Tile1 {
    coordinates = Point(x=0, y=0)
    terrainType = Grassland
}

object Tile2 {
    coordinates = Point(x=1, y=0)
    terrainType = Grassland
}

object Tile3 {
    coordinates = Point(x=0, y=1)
    terrainType = Forest
}

object Tile4 {
    coordinates = Point(x=1, y=1)
    terrainType = Forest
}

object Character1 {
    location = Point(x=0, y=0)
}

object Transport1 {
    location = Point(x=1, y=1)
}

object Grassland {
}

object Forest {
}

World "1" --> "1" TimeInstance
World "1" --> "*" Map1
World "1" --> "*" Map2
World "1" --> "*" Character1
World "1" --> "*" Transport1
Map1 "1" --> "*" Tile1
Map1 "1" --> "*" Tile2
Map2 "1" --> "*" Tile3
Map2 "1" --> "*" Tile4
Character1 "n" -down- "0..1" Transport1

@enduml
