@startuml
skin rose
title Caso de Uso: Advance Time

state SYSTEM_ACTIVE as "System Active"
state AdvanceTime as "Advance Time"
state UpdateImpreciseTime as "Update Imprecise Time"

[*] --> SYSTEM_ACTIVE
SYSTEM_ACTIVE -[#blue]-> AdvanceTime : System allows advancing time
AdvanceTime -[#blue]-> UpdateImpreciseTime : System advances time
UpdateImpreciseTime -[#blue]-> SYSTEM_ACTIVE : Time updated

@enduml
