@startuml
skin rose
title Caso de Uso: Execute Simulation Cycle

state SIMULATION_RUNNING as "Simulation Running"
state ExecuteSimulationCycle as "Execute Simulation Cycle"
state MoveTime as "Move Time"
state MoveNPC as "Move NPC"
state InitializeMap as "Initialize Map"
state InitializeEntities as "Initialize Entities"
state MoveTransport as "Move Transport"

[*] --> SIMULATION_RUNNING
SIMULATION_RUNNING -[#blue]-> ExecuteSimulationCycle : System executes simulation cycle
ExecuteSimulationCycle -[#blue]-> MoveTime : System moves time
MoveTime -[#blue]-> MoveNPC : System moves non-player characters
MoveNPC -[#blue]-> InitializeMap : System initializes map
InitializeMap -[#blue]-> InitializeEntities : System initializes entities
InitializeEntities -[#blue]-> MoveTransport : System moves transport
MoveTransport -[#blue]-> SIMULATION_RUNNING : Simulation cycle complete

@enduml
