@startuml
skin rose
title Caso de Uso: Update Transport

state SIMULATION_ACTIVE as "Simulation Active"
state CheckTile as "Check Player's Tile"
state AssignTransport as "Assign Transport"

[*] --> SIMULATION_ACTIVE
SIMULATION_ACTIVE -[#blue]-> CheckTile : System checks player's tile
CheckTile -[#blue]-> AssignTransport : Transport determined
AssignTransport -[#blue]-> SIMULATION_ACTIVE : Transport assigned to player

@enduml
