@startuml
skin rose
title Caso de Uso: Move Transport

state SIMULATION_RUNNING as "Simulation Running"
state MoveTransport as "Move Transport"
state UpdateTransportPosition as "Update Transport Position"

[*] --> SIMULATION_RUNNING
SIMULATION_RUNNING -[#blue]-> MoveTransport : System moves transport
MoveTransport -[#blue]-> UpdateTransportPosition : System updates transport positions
UpdateTransportPosition -[#blue]-> SIMULATION_RUNNING : Transport positions updated

@enduml
